"""update

Revision ID: 703670ce36ed
Revises: ae10752be460
Create Date: 2023-05-26 03:27:23.530597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "703670ce36ed"
down_revision = "ae10752be460"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
