version: "3.0"
services:

  mongodb:
    container_name: mongodb
    image: mongo # use the latest image.
    restart: always
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    # volumes: # optional to preserve database after container is deleted.
    #   - ./database-data:/data/db
    networks:
      - custom
  
  # Mongo Express Service
  mongo-express:
    container_name: mongo-express
    image: mongo-express # latest image
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongodb 
      # use the name of the mongo container above for server env var.
      # In our case this is mongodb
    networks:
      - custom

  postgres:
    container_name: "postgres"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
